"C:\Program Files\Inkscape\inkscape.exe" .\src\color\deprecated\bevaix.svg -e .\pngs\deprecated\bevaix.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\deprecated\brot-dessous.svg -e .\pngs\deprecated\brot-dessous.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\deprecated\fresens.svg -e .\pngs\deprecated\fresens.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\deprecated\gorgier.svg -e .\pngs\deprecated\gorgier.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\deprecated\montalchez.svg -e .\pngs\deprecated\montalchez.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\deprecated\saint-aubin-sauges.svg -e .\pngs\deprecated\saint-aubin-sauges.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\deprecated\vaumarcus.svg -e .\pngs\deprecated\vaumarcus.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\boudry.svg -e .\pngs\boudry.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\brot-plamboz.svg -e .\pngs\brot-plamboz.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\corcelles_cormondreche.svg -e .\pngs\corcelles_cormondreche.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\cornaux.svg -e .\pngs\cornaux.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\cortaillod.svg -e .\pngs\cortaillod.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\cressier.svg -e .\pngs\cressier.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\enges.svg -e .\pngs\enges.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\hauterive.svg -e .\pngs\hauterive.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\la_brevine.svg -e .\pngs\la_brevine.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\la_chaux-de-fonds.svg -e .\pngs\la_chaux-de-fonds.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\la_chaux-du-milieu.svg -e .\pngs\la_chaux-du-milieu.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\la_cote-aux-fees.svg -e .\pngs\la_cote-aux-fees.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\la_grande-beroche.svg -e .\pngs\la_grande-beroche.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\la_sagne.svg -e .\pngs\la_sagne.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\la_tene.svg -e .\pngs\la_tene.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\les_brenets.svg -e .\pngs\les_brenets.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\les_planchettes.svg -e .\pngs\les_planchettes.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\les_ponts-de-martel.svg -e .\pngs\les_ponts-de-martel.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\les_verrieres.svg -e .\pngs\les_verrieres.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\le_cerneux-pequignot.svg -e .\pngs\le_cerneux-pequignot.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\le_landeron.svg -e .\pngs\le_landeron.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\le_locle.svg -e .\pngs\le_locle.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\lignieres.svg -e .\pngs\lignieres.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\milvignes.svg -e .\pngs\milvignes.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\neuchatel.svg -e .\pngs\neuchatel.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\peseux.svg -e .\pngs\peseux.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\rochefort.svg -e .\pngs\rochefort.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\saint-blaise.svg -e .\pngs\saint-blaise.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\val-de-ruz.svg -e .\pngs\val-de-ruz.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\val-de-travers.svg -e .\pngs\val-de-travers.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\valangin.svg -e .\pngs\valangin.png