"C:\Program Files\Inkscape\inkscape.exe" .\src\color\boudry.svg -e .\pngs\color\boudry.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\brot-plamboz.svg -e .\pngs\color\brot-plamboz.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\corcelles_cormondreche.svg -e .\pngs\color\corcelles_cormondreche.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\cornaux.svg -e .\pngs\color\cornaux.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\cortaillod.svg -e .\pngs\color\cortaillod.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\cressier.svg -e .\pngs\color\cressier.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\enges.svg -e .\pngs\color\enges.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\hauterive.svg -e .\pngs\color\hauterive.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\la_brevine.svg -e .\pngs\color\la_brevine.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\la_chaux-de-fonds.svg -e .\pngs\color\la_chaux-de-fonds.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\la_chaux-du-milieu.svg -e .\pngs\color\la_chaux-du-milieu.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\la_cote-aux-fees.svg -e .\pngs\color\la_cote-aux-fees.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\la_grande-beroche.svg -e .\pngs\color\la_grande-beroche.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\la_sagne.svg -e .\pngs\color\la_sagne.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\la_tene.svg -e .\pngs\color\la_tene.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\les_brenets.svg -e .\pngs\color\les_brenets.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\les_planchettes.svg -e .\pngs\color\les_planchettes.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\les_ponts-de-martel.svg -e .\pngs\color\les_ponts-de-martel.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\les_verrieres.svg -e .\pngs\color\les_verrieres.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\le_cerneux-pequignot.svg -e .\pngs\color\le_cerneux-pequignot.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\le_landeron.svg -e .\pngs\color\le_landeron.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\le_locle.svg -e .\pngs\color\le_locle.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\lignieres.svg -e .\pngs\color\lignieres.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\milvignes.svg -e .\pngs\color\milvignes.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\neuchatel.svg -e .\pngs\color\neuchatel.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\peseux.svg -e .\pngs\color\peseux.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\rochefort.svg -e .\pngs\color\rochefort.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\saint-blaise.svg -e .\pngs\color\saint-blaise.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\val-de-ruz.svg -e .\pngs\color\val-de-ruz.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\val-de-travers.svg -e .\pngs\color\val-de-travers.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\color\valangin.svg -e .\pngs\color\valangin.png

"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\boudry.svg -e .\pngs\outlined\boudry.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\brot-plamboz.svg -e .\pngs\outlined\brot-plamboz.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\corcelles_cormondreche.svg -e .\pngs\outlined\corcelles_cormondreche.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\cornaux.svg -e .\pngs\outlined\cornaux.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\cortaillod.svg -e .\pngs\outlined\cortaillod.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\cressier.svg -e .\pngs\outlined\cressier.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\enges.svg -e .\pngs\outlined\enges.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\hauterive.svg -e .\pngs\outlined\hauterive.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\la_brevine.svg -e .\pngs\outlined\la_brevine.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\la_chaux-de-fonds.svg -e .\pngs\outlined\la_chaux-de-fonds.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\la_chaux-du-milieu.svg -e .\pngs\outlined\la_chaux-du-milieu.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\la_cote-aux-fees.svg -e .\pngs\outlined\la_cote-aux-fees.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\la_grande-beroche.svg -e .\pngs\outlined\la_grande-beroche.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\la_sagne.svg -e .\pngs\outlined\la_sagne.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\la_tene.svg -e .\pngs\outlined\la_tene.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\les_brenets.svg -e .\pngs\outlined\les_brenets.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\les_planchettes.svg -e .\pngs\outlined\les_planchettes.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\les_ponts-de-martel.svg -e .\pngs\outlined\les_ponts-de-martel.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\les_verrieres.svg -e .\pngs\outlined\les_verrieres.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\le_cerneux-pequignot.svg -e .\pngs\outlined\le_cerneux-pequignot.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\le_landeron.svg -e .\pngs\outlined\le_landeron.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\le_locle.svg -e .\pngs\outlined\le_locle.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\lignieres.svg -e .\pngs\outlined\lignieres.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\milvignes.svg -e .\pngs\outlined\milvignes.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\neuchatel.svg -e .\pngs\outlined\neuchatel.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\peseux.svg -e .\pngs\outlined\peseux.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\rochefort.svg -e .\pngs\outlined\rochefort.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\saint-blaise.svg -e .\pngs\outlined\saint-blaise.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\val-de-ruz.svg -e .\pngs\outlined\val-de-ruz.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\val-de-travers.svg -e .\pngs\outlined\val-de-travers.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\outlined\valangin.svg -e .\pngs\outlined\valangin.png

"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\boudry.svg -e .\pngs\simplified\boudry.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\brot-plamboz.svg -e .\pngs\simplified\brot-plamboz.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\corcelles_cormondreche.svg -e .\pngs\simplified\corcelles_cormondreche.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\cornaux.svg -e .\pngs\simplified\cornaux.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\cortaillod.svg -e .\pngs\simplified\cortaillod.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\cressier.svg -e .\pngs\simplified\cressier.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\enges.svg -e .\pngs\simplified\enges.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\hauterive.svg -e .\pngs\simplified\hauterive.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\la_brevine.svg -e .\pngs\simplified\la_brevine.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\la_chaux-de-fonds.svg -e .\pngs\simplified\la_chaux-de-fonds.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\la_chaux-du-milieu.svg -e .\pngs\simplified\la_chaux-du-milieu.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\la_cote-aux-fees.svg -e .\pngs\simplified\la_cote-aux-fees.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\la_grande-beroche.svg -e .\pngs\simplified\la_grande-beroche.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\la_sagne.svg -e .\pngs\simplified\la_sagne.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\la_tene.svg -e .\pngs\simplified\la_tene.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\les_brenets.svg -e .\pngs\simplified\les_brenets.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\les_planchettes.svg -e .\pngs\simplified\les_planchettes.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\les_ponts-de-martel.svg -e .\pngs\simplified\les_ponts-de-martel.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\les_verrieres.svg -e .\pngs\simplified\les_verrieres.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\le_cerneux-pequignot.svg -e .\pngs\simplified\le_cerneux-pequignot.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\le_landeron.svg -e .\pngs\simplified\le_landeron.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\le_locle.svg -e .\pngs\simplified\le_locle.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\lignieres.svg -e .\pngs\simplified\lignieres.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\milvignes.svg -e .\pngs\simplified\milvignes.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\neuchatel.svg -e .\pngs\simplified\neuchatel.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\peseux.svg -e .\pngs\simplified\peseux.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\rochefort.svg -e .\pngs\simplified\rochefort.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\saint-blaise.svg -e .\pngs\simplified\saint-blaise.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\val-de-ruz.svg -e .\pngs\simplified\val-de-ruz.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\val-de-travers.svg -e .\pngs\simplified\val-de-travers.png
"C:\Program Files\Inkscape\inkscape.exe" .\src\simplified\valangin.svg -e .\pngs\simplified\valangin.png